// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAhpL4z6mTUCgrTVzy8WNPRVPOXy1BLnA',
    appId: '1:503054691567:web:2b7df81584d901d749bf1a',
    messagingSenderId: '503054691567',
    projectId: 'fir-distribution-bizflow',
    authDomain: 'fir-distribution-bizflow.firebaseapp.com',
    storageBucket: 'fir-distribution-bizflow.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClPjmZ-yYiuwi1Ra4gGebMX-vHjAg7UD0',
    appId: '1:503054691567:android:8b22662982ae0d6f49bf1a',
    messagingSenderId: '503054691567',
    projectId: 'fir-distribution-bizflow',
    storageBucket: 'fir-distribution-bizflow.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJaGK1XZax_fGFXStIQmwzSY_Uiqa8btw',
    appId: '1:503054691567:ios:08905276e748c4e549bf1a',
    messagingSenderId: '503054691567',
    projectId: 'fir-distribution-bizflow',
    storageBucket: 'fir-distribution-bizflow.appspot.com',
    iosBundleId: 'com.example.bizflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJaGK1XZax_fGFXStIQmwzSY_Uiqa8btw',
    appId: '1:503054691567:ios:08905276e748c4e549bf1a',
    messagingSenderId: '503054691567',
    projectId: 'fir-distribution-bizflow',
    storageBucket: 'fir-distribution-bizflow.appspot.com',
    iosBundleId: 'com.example.bizflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAhpL4z6mTUCgrTVzy8WNPRVPOXy1BLnA',
    appId: '1:503054691567:web:ced64946d527304949bf1a',
    messagingSenderId: '503054691567',
    projectId: 'fir-distribution-bizflow',
    authDomain: 'fir-distribution-bizflow.firebaseapp.com',
    storageBucket: 'fir-distribution-bizflow.appspot.com',
  );
}
